[build]
  # Comando para construir la aplicación cliente de React
  command = "npm run build"
  
  # Directorio de construcción de la aplicación cliente
  publish = "client/build"

# Configuración para el servidor Express (API)
[[redirects]]
  from = "/api/*"
  to = "api/:splat"
  status = 200

# Redireccionar todas las demás rutas a la aplicación cliente
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
